### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by aeosynth** [orlandov/node-sqlite#10]
It would be nice if you provided a function to escape sql statements.

**Comment by orlandov** [comment]
What are you trying to escape? You can escape out of the box by using place holders (? or :foo) in you SQL.

db.execute("SELECT \* FROM fruit WHERE apples=?", [10], callback)

**Comment by aeosynth** [comment]
I'm trying to escape user input. I'm doing something wrong, because I get errors executing this script:

```
var sqlite = require('sqlite');
var db = new sqlite.Database();

function callback (error, rows) {
    if (error) {
        console.log("Error in callback");
        throw error;
    }
    console.log(rows);
}

db.open("fruit", function (error) {
    if (error) {
        console.log("Error opening db");
        throw error;
    }
    db.execute("SELECT * FROM fruit WHERE apples=?", [10], callback);
});
```

output:
    [james@arch tmp]$ node -v
    v0.2.4
    [james@arch tmp]$ node fruit.js

```
/home/james/.node_libraries/.npm/sqlite/0.0.5/package/sqlite.js:108
      statement.bind(bindings, function (error) {
                ^
TypeError: Argument 2 must be a function
    at /home/james/.node_libraries/.npm/sqlite/0.0.5/package/sqlite.js:108:17
    at node.js:772:9
```

**Comment by orlandov** [comment]
Hey, thanks for the report. If you have the most recent tagged version (0.0.6) from NPM or github, this should be fixed.

**Comment by aeosynth** [comment]
Awesome, everything works now. I didn't know that place holders were auto-escaped, since that's not mentioned anywhere in the readme.
