### ISSUE TITLE
Non-NULL zero-length strings cause a crash

### ISSUE THREAD

**Issue by carter-thaxton** [orlandov/node-sqlite#3]
statement.cc, line 507, asserts that the text coming out of sqlite have a non-zero length.
This is not always the case.  NULL and the empty string are considered different values.
I've simply commented out the assertion locally, and this fixes the problem.

```
    case SQLITE_TEXT:
      assert(strlen((char*)sto->column_data_[i]));            //  <-----  broken
      row->Set(String::NewSymbol(sto->column_names_[i]),
               String::New((char *) (sto->column_data_[i])));
```

**Comment by orlandov** [comment]
Thanks! Fixed in e204b6
