### ISSUE TITLE
Text variable bindings appear to work, but then can't be used in WHERE clauses!

### ISSUE THREAD

**Issue by carter-thaxton** [orlandov/node-sqlite#5]
Execute some SQL like this, using the node-sqlite library:
INSERT INTO tbl (foo) VALUES (?)
and use a string bind value, like ['abc']

For example:
db.query("INSERT INTO tbl (foo) VALUES (?)", ['abc'], function() {});

If you open up a sqlite3 console, you'll see your new row.  Yet the following query will return no rows:
   SELECT \* FROM tbl WHERE foo = 'abc'

You can see them right there.  What's wrong?

After a good deal of debugging time, I found the culprit.

In statement.cc, the various Bind, BindArray, BindObjects, store value_size as the total C string length, including the NUL terminator.

For example, around line 200, there is:
    else if (val->IsString()) {
      pairs->value_type = VALUE_STRING;
      String::Utf8Value text(val);
      char _value = (char *) calloc(text.length()+1, sizeof(char_));
      strcpy(value, *text);
      pairs->value = value;
      pairs->value_size = text.length()+1;       // <----  right here
    }

Then in EIO_BindArray, around line 133:

```
  case VALUE_STRING:
    rc = sqlite3_bind_text(sto->stmt_, index, (char*)(pair->value),
        pair->value_size, SQLITE_TRANSIENT);       //  <---  value_size
    break;
```

I just changed it to use:
            pair->value_size-1, SQLITE_TRANSIENT);

and everything works great!

On query, the values are NUL-terminated again while converting to JS strings.  I noticed that all of your tests simply ensure that the text binds come back via a SELECT, which wouldn't catch this.

The sqlite3 documentation isn't very good at describing the 'n' parameter to sqlite3_bind_text().
I guess we just found out the hard way that it shouldn't include any terminators.

I tried a few UTF-8 Japanese strings, empty strings, null, etc, and they all work great with this change.

Hope this helps!
- Carter

**Comment by orlandov** [comment]
Closing old issues....
