### ISSUE TITLE
Please publish to npm

### ISSUE THREAD

**Issue by pkrumins** [orlandov/node-sqlite#7]
Please don't forget to keep your github repository and npm in sync.

Currently you have old version 0.0.2 in npm and zizzy knows which version here on github.

So annoying.

**Comment by orlandov** [comment]
I haven't forgotten. I'll publish to NPM when I feel I'm ready to do so.

P.S. It's totally unnecessary to terminate your messages with "(So|Very) annoying". That's "very annoying".

**Comment by pkrumins** [comment]
I published it as pksqlite :)

Never mind my so annoying messages, I was just so annoyed that I wanted to say I felt that way.
