### ISSUE TITLE
Error on bind 

### ISSUE THREAD

**Issue by mrjjwright** [orlandov/node-sqlite#9]
The following code is throwing an error: http://gist.github.com/641672.  I am having trouble finding the root cause in the code.  The line in sqlite.js is at a bind call but the only place that error is thrown is inside database.prepare inside the cc file.

**Comment by orlandov** [comment]
Hey John, thanks for the report. This bug should be fixed in version 0.0.6.

**Comment by mrjjwright** [comment]
Thanks so much!
